name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # or the branch you want to trigger deployments from

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Use Node.js v18.x or change to a later version if needed

      - name: Install Dependencies
        run: npm install

      - name: Deploy to Firebase
        run: firebase deploy --only hosting --non-interactive
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
